/* tslint:disable */
/* eslint-disable */
/**
 * Movie Database API
 * API für Filme, Favoriten und Empfehlungen
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface ApiMoviesIdActorsGetRequest {
    id: number;
}

export interface ApiMoviesIdDirectorsGetRequest {
    id: number;
}

export interface ApiMoviesIdFavoriteDeleteRequest {
    id: number;
}

export interface ApiMoviesIdFavoritePostRequest {
    id: number;
}

export interface ApiMoviesIdGetRequest {
    id: number;
}

export interface ApiMoviesIdMainActorGetRequest {
    id: number;
}

export interface ApiMoviesIdMainActorNameGetRequest {
    id: number;
}

export interface ApiMoviesIdRatingDeleteRequest {
    id: number;
}

export interface ApiMoviesIdRatingPostRequest {
    id: number;
    body?: number;
}

/**
 * 
 */
export class MoviesApi extends runtime.BaseAPI {

    /**
     */
    async apiMoviesFavoritesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Movies/favorites`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiMoviesFavoritesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiMoviesFavoritesGetRaw(initOverrides);
    }

    /**
     */
    async apiMoviesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Movies`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiMoviesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiMoviesGetRaw(initOverrides);
    }

    /**
     */
    async apiMoviesIdActorsGetRaw(requestParameters: ApiMoviesIdActorsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMoviesIdActorsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Movies/{id}/actors`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiMoviesIdActorsGet(requestParameters: ApiMoviesIdActorsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiMoviesIdActorsGetRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiMoviesIdDirectorsGetRaw(requestParameters: ApiMoviesIdDirectorsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMoviesIdDirectorsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Movies/{id}/directors`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiMoviesIdDirectorsGet(requestParameters: ApiMoviesIdDirectorsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiMoviesIdDirectorsGetRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiMoviesIdFavoriteDeleteRaw(requestParameters: ApiMoviesIdFavoriteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMoviesIdFavoriteDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Movies/{id}/favorite`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiMoviesIdFavoriteDelete(requestParameters: ApiMoviesIdFavoriteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiMoviesIdFavoriteDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiMoviesIdFavoritePostRaw(requestParameters: ApiMoviesIdFavoritePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMoviesIdFavoritePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Movies/{id}/favorite`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiMoviesIdFavoritePost(requestParameters: ApiMoviesIdFavoritePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiMoviesIdFavoritePostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiMoviesIdGetRaw(requestParameters: ApiMoviesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMoviesIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Movies/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiMoviesIdGet(requestParameters: ApiMoviesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiMoviesIdGetRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiMoviesIdMainActorGetRaw(requestParameters: ApiMoviesIdMainActorGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMoviesIdMainActorGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Movies/{id}/main-actor`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiMoviesIdMainActorGet(requestParameters: ApiMoviesIdMainActorGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiMoviesIdMainActorGetRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiMoviesIdMainActorNameGetRaw(requestParameters: ApiMoviesIdMainActorNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMoviesIdMainActorNameGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Movies/{id}/main-actor-name`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiMoviesIdMainActorNameGet(requestParameters: ApiMoviesIdMainActorNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiMoviesIdMainActorNameGetRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiMoviesIdRatingDeleteRaw(requestParameters: ApiMoviesIdRatingDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMoviesIdRatingDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Movies/{id}/rating`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiMoviesIdRatingDelete(requestParameters: ApiMoviesIdRatingDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiMoviesIdRatingDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiMoviesIdRatingPostRaw(requestParameters: ApiMoviesIdRatingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMoviesIdRatingPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/Movies/{id}/rating`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiMoviesIdRatingPost(requestParameters: ApiMoviesIdRatingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiMoviesIdRatingPostRaw(requestParameters, initOverrides);
    }

}
