/* tslint:disable */
/* eslint-disable */
/**
 * Movie Database API
 * API für Filme, Favoriten und Empfehlungen
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface ApiRecommendationsDebugNeo4jMoviesGetRequest {
    limit?: number;
}

export interface ApiRecommendationsDebugSimpleGetRequest {
    count?: number;
}

export interface ApiRecommendationsMovieMovieIdGetRequest {
    movieId: number;
    count?: number;
    type?: string;
}

export interface ApiRecommendationsPopularGetRequest {
    count?: number;
}

/**
 * 
 */
export class RecommendationsApi extends runtime.BaseAPI {

    /**
     */
    async apiRecommendationsDebugAnalyzeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Recommendations/debug/analyze`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiRecommendationsDebugAnalyzeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiRecommendationsDebugAnalyzeGetRaw(initOverrides);
    }

    /**
     */
    async apiRecommendationsDebugNeo4jMoviesGetRaw(requestParameters: ApiRecommendationsDebugNeo4jMoviesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Recommendations/debug/neo4j-movies`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiRecommendationsDebugNeo4jMoviesGet(requestParameters: ApiRecommendationsDebugNeo4jMoviesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiRecommendationsDebugNeo4jMoviesGetRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiRecommendationsDebugSimpleGetRaw(requestParameters: ApiRecommendationsDebugSimpleGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['count'] != null) {
            queryParameters['count'] = requestParameters['count'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Recommendations/debug/simple`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiRecommendationsDebugSimpleGet(requestParameters: ApiRecommendationsDebugSimpleGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiRecommendationsDebugSimpleGetRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiRecommendationsMovieMovieIdGetRaw(requestParameters: ApiRecommendationsMovieMovieIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<any>>> {
        if (requestParameters['movieId'] == null) {
            throw new runtime.RequiredError(
                'movieId',
                'Required parameter "movieId" was null or undefined when calling apiRecommendationsMovieMovieIdGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['count'] != null) {
            queryParameters['count'] = requestParameters['count'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Recommendations/movie/{movieId}`.replace(`{${"movieId"}}`, encodeURIComponent(String(requestParameters['movieId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async apiRecommendationsMovieMovieIdGet(requestParameters: ApiRecommendationsMovieMovieIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<any>> {
        const response = await this.apiRecommendationsMovieMovieIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiRecommendationsPopularGetRaw(requestParameters: ApiRecommendationsPopularGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<any>>> {
        const queryParameters: any = {};

        if (requestParameters['count'] != null) {
            queryParameters['count'] = requestParameters['count'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Recommendations/popular`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async apiRecommendationsPopularGet(requestParameters: ApiRecommendationsPopularGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<any>> {
        const response = await this.apiRecommendationsPopularGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiRecommendationsTestGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Recommendations/test`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiRecommendationsTestGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiRecommendationsTestGetRaw(initOverrides);
    }

}
