/* tslint:disable */
/* eslint-disable */
/**
 * Movie Database API
 * Eine API für Filme, Personen, Genres, Favoriten und Empfehlungen
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

/**
 * 
 */
export class MoviesAPIApi extends runtime.BaseAPI {

    /**
     */
    async testRepositoryGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/test-repository`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async testRepositoryGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.testRepositoryGetRaw(initOverrides);
    }

}
