/* tslint:disable */
/* eslint-disable */
/**
 * Movie Database API
 * Eine API für Filme, Personen, Genres, Favoriten und Empfehlungen
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MovieDto,
  ProblemDetails,
} from '../models/index';
import {
    MovieDtoFromJSON,
    MovieDtoToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/index';

export interface ApiMoviesIdActorsGetRequest {
    id: number;
}

export interface ApiMoviesIdDetailsGetRequest {
    id: number;
}

export interface ApiMoviesIdDirectorsGetRequest {
    id: number;
}

export interface ApiMoviesIdFavoriteDeleteRequest {
    id: number;
}

export interface ApiMoviesIdFavoritePostRequest {
    id: number;
}

export interface ApiMoviesIdGenresGetRequest {
    id: number;
}

export interface ApiMoviesIdGetRequest {
    id: number;
}

export interface ApiMoviesIdIsfavoriteGetRequest {
    id: number;
}

export interface ApiMoviesIdRatingGetRequest {
    id: number;
}

export interface ApiMoviesIdUserratingDeleteRequest {
    id: number;
}

export interface ApiMoviesIdUserratingGetRequest {
    id: number;
}

export interface ApiMoviesIdUserratingPostRequest {
    id: number;
    body?: number;
}

export interface ApiMoviesSearchGetRequest {
    query?: string;
}

export interface ApiMoviesTopCountGetRequest {
    count: number;
}

export interface ApiMoviesYearYearGetRequest {
    year: number;
}

/**
 * 
 */
export class MoviesApi extends runtime.BaseAPI {

    /**
     */
    async apiMoviesDatagridGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MovieDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Movies/datagrid`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MovieDtoFromJSON));
    }

    /**
     */
    async apiMoviesDatagridGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MovieDto>> {
        const response = await this.apiMoviesDatagridGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiMoviesFavoritesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MovieDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Movies/favorites`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MovieDtoFromJSON));
    }

    /**
     */
    async apiMoviesFavoritesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MovieDto>> {
        const response = await this.apiMoviesFavoritesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiMoviesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MovieDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Movies`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MovieDtoFromJSON));
    }

    /**
     */
    async apiMoviesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MovieDto>> {
        const response = await this.apiMoviesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiMoviesIdActorsGetRaw(requestParameters: ApiMoviesIdActorsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMoviesIdActorsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Movies/{id}/actors`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async apiMoviesIdActorsGet(requestParameters: ApiMoviesIdActorsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.apiMoviesIdActorsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiMoviesIdDetailsGetRaw(requestParameters: ApiMoviesIdDetailsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMoviesIdDetailsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Movies/{id}/details`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiMoviesIdDetailsGet(requestParameters: ApiMoviesIdDetailsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiMoviesIdDetailsGetRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiMoviesIdDirectorsGetRaw(requestParameters: ApiMoviesIdDirectorsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMoviesIdDirectorsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Movies/{id}/directors`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async apiMoviesIdDirectorsGet(requestParameters: ApiMoviesIdDirectorsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.apiMoviesIdDirectorsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiMoviesIdFavoriteDeleteRaw(requestParameters: ApiMoviesIdFavoriteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMoviesIdFavoriteDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Movies/{id}/favorite`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiMoviesIdFavoriteDelete(requestParameters: ApiMoviesIdFavoriteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiMoviesIdFavoriteDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiMoviesIdFavoritePostRaw(requestParameters: ApiMoviesIdFavoritePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMoviesIdFavoritePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Movies/{id}/favorite`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiMoviesIdFavoritePost(requestParameters: ApiMoviesIdFavoritePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiMoviesIdFavoritePostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiMoviesIdGenresGetRaw(requestParameters: ApiMoviesIdGenresGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMoviesIdGenresGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Movies/{id}/genres`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async apiMoviesIdGenresGet(requestParameters: ApiMoviesIdGenresGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.apiMoviesIdGenresGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiMoviesIdGetRaw(requestParameters: ApiMoviesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MovieDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMoviesIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Movies/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MovieDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiMoviesIdGet(requestParameters: ApiMoviesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MovieDto> {
        const response = await this.apiMoviesIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiMoviesIdIsfavoriteGetRaw(requestParameters: ApiMoviesIdIsfavoriteGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMoviesIdIsfavoriteGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Movies/{id}/isfavorite`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async apiMoviesIdIsfavoriteGet(requestParameters: ApiMoviesIdIsfavoriteGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.apiMoviesIdIsfavoriteGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiMoviesIdRatingGetRaw(requestParameters: ApiMoviesIdRatingGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMoviesIdRatingGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Movies/{id}/rating`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async apiMoviesIdRatingGet(requestParameters: ApiMoviesIdRatingGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.apiMoviesIdRatingGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiMoviesIdUserratingDeleteRaw(requestParameters: ApiMoviesIdUserratingDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMoviesIdUserratingDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Movies/{id}/userrating`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiMoviesIdUserratingDelete(requestParameters: ApiMoviesIdUserratingDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiMoviesIdUserratingDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiMoviesIdUserratingGetRaw(requestParameters: ApiMoviesIdUserratingGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMoviesIdUserratingGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Movies/{id}/userrating`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async apiMoviesIdUserratingGet(requestParameters: ApiMoviesIdUserratingGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.apiMoviesIdUserratingGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiMoviesIdUserratingPostRaw(requestParameters: ApiMoviesIdUserratingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMoviesIdUserratingPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/Movies/{id}/userrating`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiMoviesIdUserratingPost(requestParameters: ApiMoviesIdUserratingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiMoviesIdUserratingPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiMoviesSearchGetRaw(requestParameters: ApiMoviesSearchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MovieDto>>> {
        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Movies/search`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MovieDtoFromJSON));
    }

    /**
     */
    async apiMoviesSearchGet(requestParameters: ApiMoviesSearchGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MovieDto>> {
        const response = await this.apiMoviesSearchGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiMoviesTopCountGetRaw(requestParameters: ApiMoviesTopCountGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MovieDto>>> {
        if (requestParameters['count'] == null) {
            throw new runtime.RequiredError(
                'count',
                'Required parameter "count" was null or undefined when calling apiMoviesTopCountGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Movies/top/{count}`.replace(`{${"count"}}`, encodeURIComponent(String(requestParameters['count']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MovieDtoFromJSON));
    }

    /**
     */
    async apiMoviesTopCountGet(requestParameters: ApiMoviesTopCountGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MovieDto>> {
        const response = await this.apiMoviesTopCountGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiMoviesYearYearGetRaw(requestParameters: ApiMoviesYearYearGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MovieDto>>> {
        if (requestParameters['year'] == null) {
            throw new runtime.RequiredError(
                'year',
                'Required parameter "year" was null or undefined when calling apiMoviesYearYearGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Movies/year/{year}`.replace(`{${"year"}}`, encodeURIComponent(String(requestParameters['year']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MovieDtoFromJSON));
    }

    /**
     */
    async apiMoviesYearYearGet(requestParameters: ApiMoviesYearYearGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MovieDto>> {
        const response = await this.apiMoviesYearYearGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}