/* tslint:disable */
/* eslint-disable */
/**
 * Movie Database API
 * Eine API für Filme, Personen, Genres, Favoriten und Empfehlungen
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ProblemDetails,
} from '../models/index';
import {
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/index';

export interface ApiRecommendationsMovieMovieIdGetRequest {
    movieId: number;
    type?: string;
    count?: number;
}

export interface ApiRecommendationsSimpleGetRequest {
    count?: number;
}

/**
 * 
 */
export class RecommendationsApi extends runtime.BaseAPI {

    /**
     */
    async apiRecommendationsMovieMovieIdGetRaw(requestParameters: ApiRecommendationsMovieMovieIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['movieId'] == null) {
            throw new runtime.RequiredError(
                'movieId',
                'Required parameter "movieId" was null or undefined when calling apiRecommendationsMovieMovieIdGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['count'] != null) {
            queryParameters['count'] = requestParameters['count'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Recommendations/movie/{movieId}`.replace(`{${"movieId"}}`, encodeURIComponent(String(requestParameters['movieId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiRecommendationsMovieMovieIdGet(requestParameters: ApiRecommendationsMovieMovieIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiRecommendationsMovieMovieIdGetRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiRecommendationsSimpleGetRaw(requestParameters: ApiRecommendationsSimpleGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['count'] != null) {
            queryParameters['count'] = requestParameters['count'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Recommendations/simple`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiRecommendationsSimpleGet(requestParameters: ApiRecommendationsSimpleGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiRecommendationsSimpleGetRaw(requestParameters, initOverrides);
    }

}