/* tslint:disable */
/* eslint-disable */
/**
 * Movie Database API
 * Eine API für Filme, Personen, Genres, Favoriten und Empfehlungen
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

/**
 * 
 */
export class TestApi extends runtime.BaseAPI {

    /**
     */
    async apiTestDatabasesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Test/databases`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiTestDatabasesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiTestDatabasesGetRaw(initOverrides);
    }

    /**
     */
    async apiTestFavoritesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Test/favorites`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiTestFavoritesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiTestFavoritesGetRaw(initOverrides);
    }

    /**
     */
    async apiTestRepositoryGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Test/repository`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiTestRepositoryGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiTestRepositoryGetRaw(initOverrides);
    }

}