/* tslint:disable */
/* eslint-disable */
/**
 * Movie Database API
 * Eine API für Filme, Personen, Genres, Favoriten und Empfehlungen
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MovieDto
 */
export interface MovieDto {
    /**
     * 
     * @type {number}
     * @memberof MovieDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof MovieDto
     */
    title?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MovieDto
     */
    released?: number;
    /**
     * 
     * @type {number}
     * @memberof MovieDto
     */
    rating?: number | null;
    /**
     * 
     * @type {string}
     * @memberof MovieDto
     */
    summary?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MovieDto
     */
    tagline?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof MovieDto
     */
    isFavorite?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MovieDto
     */
    actors?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MovieDto
     */
    userRating?: number | null;
}

/**
 * Check if a given object implements the MovieDto interface.
 */
export function instanceOfMovieDto(value: object): value is MovieDto {
    return true;
}

export function MovieDtoFromJSON(json: any): MovieDto {
    return MovieDtoFromJSONTyped(json, false);
}

export function MovieDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'released': json['released'] == null ? undefined : json['released'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'tagline': json['tagline'] == null ? undefined : json['tagline'],
        'isFavorite': json['isFavorite'] == null ? undefined : json['isFavorite'],
        'actors': json['actors'] == null ? undefined : json['actors'],
        'userRating': json['userRating'] == null ? undefined : json['userRating'],
    };
}

export function MovieDtoToJSON(json: any): MovieDto {
    return MovieDtoToJSONTyped(json, false);
}

export function MovieDtoToJSONTyped(value?: MovieDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'released': value['released'],
        'rating': value['rating'],
        'summary': value['summary'],
        'tagline': value['tagline'],
        'isFavorite': value['isFavorite'],
        'actors': value['actors'],
        'userRating': value['userRating'],
    };
}
